{% set name = "ccc" %}
{% set version = "1.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PSLmodels/Cost-of-Capital-Calculator/archive/refs/tags/{{ version }}.tar.gz
  sha256: c2729b5e9f554219caa8ac3f58d3dddf6748668b553b47179b50faebfc8f02a5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python >=3.6
    - taxcalc >=3.1.0
    - bokeh >=1.4.0
    - paramtools >=0.18.0

test:
  imports:
    - ccc
    - ccc.data
    - ccc.parameters
    - ccc.calculator
    - ccc.calcfunctions
    - ccc.get_taxcalc_rates
    - ccc.styles
    - ccc.controls_callback_script
    - ccc.constants
    - ccc.utils

about:
  home: https://github.com/PSLmodels/Cost-of-Capital-Calculator
  license: CC0-1.0 # see SPDX identifiers
  license_family: PUBLIC-DOMAIN
  license_file: ./docs/book/content/license.md
  summary: A cost of capital and effective tax rate calculator.
  description: |
    A cost of capital and effective tax rate calculator.
  doc_url: http://ccc.pslmodels.org/content/intro.html
  dev_url: https://github.com/PSLmodels/Cost-of-Capital-Calculator

extra:
  recipe-maintainers:
    - jdebacker
